server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tomekceszke/rsa-config
  output:
    ansi:
      enabled: ALWAYS


